Resources:
  myredshiftkmscmkkey693AA2DA:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":iam::"
                    - Ref: AWS::AccountId
                    - :root
            Resource: "*"
        Version: "2012-10-17"
      Description: Customer managed CMK key for encrypting the objects in Redshift
      EnableKeyRotation: false
      PendingWindowInDays: 7
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: CdkProjectStack/my-redshift-kms-cmk-key/Resource
  myredshiftkmscmkkeyAliasC5648C31:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/myredshiftkmscmkkey
      TargetKeyId:
        Fn::GetAtt:
          - myredshiftkmscmkkey693AA2DA
          - Arn
    Metadata:
      aws:cdk:path: CdkProjectStack/my-redshift-kms-cmk-key/Alias/Resource
  MyRedshiftCfnCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: single-node
      DBName: myredshiftdb
      MasterUsername: masterUsername
      MasterUserPassword: masterUserPassword
      NodeType: ds2.xlarge
      Encrypted: true
      KmsKeyId:
        Ref: myredshiftkmscmkkey693AA2DA
    Metadata:
      aws:cdk:path: CdkProjectStack/MyRedshiftCfnCluster
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/yWOwQrCMBBEv8V7slrBgkfp0YNQP0BqssVt00SyG0VC/t1GT/PmzWX20B5gtxnerI2dtaM75KsMZlaruuV5Ychn/Khu9DVOjgau5QdFRbT8oFFgVZ1LLBhLnS9Jnkkq9cghRYOVu+AtCQVflA8WYeLtq2mhOa4PJibSMXmhBaH/5xfCvYvqnQAAAA==
    Metadata:
      aws:cdk:path: CdkProjectStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  redshiftclusterendpoint:
    Description: RedshiftCluster Endpoint
    Value:
      Fn::GetAtt:
        - MyRedshiftCfnCluster
        - Endpoint.Address
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

